### ISSUE TITLE
Combining without repetitions doesn't work properly if source has repeated elements

### ISSUE THREAD

**Issue by robertsynoradzki** [TommasoScalici/LINQExtensions#1]
"aab".Permute(GenerateOptions.WithoutRepetition)
bears different amount of elements than

    "abc".Permute(GenerateOptions.WithoutRepetition)
as if the source was treated by `.Distinct()` inside.

This is not an expected behaviour. In math problems where source can have repeated elements (e.g. building words from a given set of letters), repeated elements should be treated uniquely.

For example, [this problem](https://mindyourdecisions.com/blog/2015/09/20/viral-math-problem-from-google-can-you-make-10-from-the-numbers-1-1-5-and-8/) cannot be easily solved because of this behavour.

Suggestion: iterate elements by index, not value.

**Comment by robertsynoradzki** [comment]
For reference, check how [this library](https://www.nuget.org/packages/Combinatorics/) does it.

**Comment by TommasoScalici** [comment]
You're right, and this should now be fixed in the latest issued commit. Let me know if you're experiencing other strange / unexpected behaviors.
